Algoritmo "EX4"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Ojevan e Henry
// Data atual  : 12/16/2024
// Professora  : Nalon
Var
// Seção de Declarações das variáveis
       i: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   i <- 15
   enquanto i <= 200 faca
      escreval("Quadrado de ", i, " = ", i * i, "")
      i <- i + 1
   fimenquanto
fimalgoritmo