Algoritmo "EX3"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Ojevan e Henry
// Data atual  : 12/16/2024
// Professora  : Nalon
Var
// Seção de Declarações das variáveis 
       i, numero: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    numero <- 101
   para i de 1 ate 10 faca
      escreva(numero, " ")
      numero <- numero + 2
   fimpara
Fimalgoritmo