Algoritmo "EX4"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Ojevan e Henry
// Data atual  : 12/16/2024
// Professora  : Nalon
Var
// Seção de Declarações das variáveis 
        i, XX: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escrevaL("Digite o valor de XX: ")
   leia(XX)
   para i de 1 ate XX faca
      escreva(i, " ")
   fimpara
Fimalgoritmo