Algoritmo "EX7"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Ojevan e Henry
// Data atual  : 12/16/2024
// Professora  : Nalon
Var
// Seção de Declarações das variáveis 
         i, soma: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     soma <- 0
   para i de 1 ate 100 faca
      soma <- soma + i
   fimpara
   escreva("Soma dos cem primeiros números: ", soma, "")
Fimalgoritmo