Algoritmo "EX3"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Ojevan e Henry
// Data atual  : 12/16/2024
// Professora  : Nalon
Var
// Seção de Declarações das variáveis 
      i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   i <- 10
   repita
      escreval(i, " ")
      i <- i - 1
   ate i < 1
Fimalgoritmo